export const styles = {
  container:         { minHeight: "100vh", background: "#0e0e0e", padding: "30px", color: "#fff" },
  title:             { color: "#ff8c00", marginBottom: "20px", fontSize: "2rem", fontWeight: "bold" },

  statusBoard:       { background: "#111", borderRadius: "14px", padding: "20px", marginBottom: "24px", borderLeft: "5px solid #ff8c00" },
  statusBoardHeader: { marginBottom: "16px" },
  statusBoardTitle:  { margin: 0, fontSize: "1.35rem", color: "#fff" },
  statusBoardSubtitle: { margin: "6px 0 0 0", color: "#aaa" },
  statusColumns:     { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "16px" },
  statusColumn:      { background: "#161616", borderRadius: "12px", padding: "14px", border: "1px solid #222" },
  columnTitle:       { margin: "0 0 12px 0", fontSize: "1rem" },
  emptyText:         { margin: 0, color: "#94a3b8" },
  taskCard:          { background: "#1b1b1b", borderRadius: "10px", padding: "12px", marginBottom: "10px", border: "1px solid #252525" },
  taskCardTop:       { display: "flex", justifyContent: "space-between", gap: "10px", alignItems: "center", marginBottom: "8px", flexWrap: "wrap" },
  taskCardText:      { margin: "0 0 5px 0", color: "#d1d5db", fontSize: "0.9rem" },
  taskCardUrgent:    { margin: "8px 0 0 0", color: "#fca5a5", fontWeight: "bold" },

  bikeCard:          { background: "#111", padding: "20px", borderRadius: "12px", borderLeft: "5px solid #ff8c00", marginBottom: "25px" },
  bikeTitle:         { margin: "0 0 10px 0", color: "#fff" },
  bikeSelected:      { color: "#ccc", margin: "0 0 12px 0" },
  bikeRow:           { display: "grid", gridTemplateColumns: "1fr 1fr 1fr 120px", gap: "10px", alignItems: "center" },
  bikeButton:        { padding: "12px", borderRadius: "8px", border: "none", background: "#ff8c00", color: "#000", fontWeight: "bold", cursor: "pointer" },
  bikeResults:       { marginTop: "12px", display: "grid", gap: "10px" },
  bikeResultItem:    { textAlign: "left", padding: "12px", borderRadius: "10px", border: "1px solid #222", background: "#1a1a1a", color: "#fff", cursor: "pointer" },

  form:              { background: "#111", padding: "20px", borderRadius: "12px", maxWidth: "650px", display: "flex", flexDirection: "column", gap: "12px", marginBottom: "40px" },
  checkboxContainer: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px", maxHeight: "200px", overflowY: "auto", padding: "10px", background: "#1a1a1a", borderRadius: "8px" },
  checkboxLabel:     { display: "flex", alignItems: "center", gap: "6px", fontSize: "0.9rem" },
  input:             { padding: "12px", borderRadius: "8px", border: "1px solid #222", background: "#1a1a1a", color: "#fff" },
  textarea:          { padding: "12px", borderRadius: "8px", border: "1px solid #222", background: "#1a1a1a", color: "#fff", minHeight: "60px" },
  previewBox:        { background: "#1a1a1a", border: "1px solid #2a2a2a", borderRadius: "10px", padding: "14px" },
  previewTitle:      { margin: "0 0 10px 0", color: "#fff", fontSize: "1rem" },
  previewText:       { margin: "0 0 6px 0", color: "#ddd" },
  button:            { padding: "12px", borderRadius: "8px", border: "none", background: "#ff8c00", color: "#000", fontWeight: "bold", cursor: "pointer" },

  timeline:          { display: "grid", gap: "18px" },
  monthSection:      { display: "grid", gap: "10px" },
  monthTitle:        { margin: "0", color: "#fff", fontSize: "1.1rem", opacity: 0.9 },
  timelineList:      { display: "grid", gap: "14px" },
  timelineItem:      { display: "grid", gridTemplateColumns: "26px 1fr", gap: "12px", alignItems: "stretch" },
  timelineLeft:      { display: "flex", flexDirection: "column", alignItems: "center" },
  dot:               { width: "12px", height: "12px", borderRadius: "50%", background: "#ff8c00", marginTop: "18px" },
  line:              { width: "2px", flex: 1, background: "#222", marginTop: "6px" },
  lineEnd:           { width: "2px", height: "12px", background: "transparent", marginTop: "6px" },
  timelineCard:      { background: "#111", padding: "18px", borderRadius: "10px", borderLeft: "5px solid #ff8c00" },
  cardTitle:         { marginBottom: "6px", fontSize: "1.2rem" },
  cardText:          { marginBottom: "4px", color: "#ccc" },
  cardNotes:         { color: "#aaa", fontStyle: "italic", marginTop: "8px" },
  advisoryBox:       { marginTop: "10px", padding: "10px 12px", borderRadius: "8px", background: "rgba(245, 158, 11, 0.12)", border: "1px solid rgba(245, 158, 11, 0.3)", color: "#fcd34d" },
  statusPill:        { padding: "5px 10px", borderRadius: "999px", color: "#fff", fontSize: "0.75rem", fontWeight: "bold" },
  cardActions:       { marginTop: "10px", display: "flex", gap: "10px" },
  editBtn:           { padding: "6px 12px", background: "#2563eb", border: "none", borderRadius: "6px", color: "#fff", cursor: "pointer" },
  deleteBtn:         { padding: "6px 12px", background: "#dc2626", border: "none", borderRadius: "6px", color: "#fff", cursor: "pointer" },
};
